services:
    ollama:
        container_name: ollama
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '11434:11434'
        volumes:
            - ./ollama_data:/root/.ollama
            - ~/.zshrc:/root/.zshrc
            - ~/.ollama_zsh_history:/root/.zsh_history
            - ~/.oh-my-zsh:/root/.oh-my-zsh
        restart: always

    openwebui:
        image: ghcr.io/open-webui/open-webui:ollama
        container_name: openwebui
        ports:
            - '3000:8080'
        volumes:
            - ./openwebui_data:/app/backend/data
            - ./ollama_data:/root/.ollama
        restart: always

    openhands:
        image: docker.all-hands.dev/all-hands-ai/openhands:0.23
        container_name: openhands
        ports:
            - '3993:3000'
        environment:
            - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.23-nikolaik
            - LOG_ALL_EVENTS=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./openhands_data:/.openhands-state
        # This is needed for the openhands container to access the host network
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        restart: always
